add signup page layout
TeamOpencampus/opencampus-legacy pull request #22
Opened 2022-04-29 18:20 UTC by thatsuman

this PR solves #5

2022-04-29 18:29 UTC, asimbera requested changes

2022-04-29 18:29 UTC, asimbera commented on src/pages/authentication/Signup.tsx
> +                I agree to pay the said amount whenever Opencampus claims
Don't. Just don't.

2022-04-29 18:29 UTC, asimbera commented on src/pages/authentication/Signup.tsx
> +              <label className='text-sm font-medium'>Confirm Password</label>
No need for confirm password field. Will add visibility toggle for password field later on.

2022-04-29 18:32 UTC, thatsuman commented on src/pages/authentication/Signup.tsx
> +                I agree to pay the said amount whenever Opencampus claims
Please allow them to stay 😢  let us do some business. Also comment a fresh checkbox for later us

2022-04-29 18:33 UTC, thatsuman commented on src/pages/authentication/Signup.tsx
> +              <label className='text-sm font-medium'>Confirm Password</label>
Ok, I'll remove it.

2022-04-29 19:21 UTC, asimbera requested changes

2022-04-29 19:21 UTC, asimbera commented on src/pages/authentication/Signup.tsx
> +              </div>
Add for attribute in label tag referencing the id of the input field.


```suggestion
              <label className='text-sm font-medium' for='firstname'>First Name</label>
              <div className='relative mt-1'>
                <input
                  type='text'
                  id='firstname'
                  className='w-full p-4 pr-12 text-sm border-gray-200 rounded-lg shadow-sm'
                  placeholder='Enter First Name'
                />
              </div>
```

Do this for all labels.

2022-04-30 05:30 UTC, asimbera approved these changes

2022-04-30 05:30 UTC, merged