add verify email page layout
TeamOpencampus/opencampus-legacy pull request #26
Opened 2022-05-01 18:11 UTC by thatsuman

Fixes #20 

Didn't add alert notification funtionality, just made the layout.

2022-05-02 18:58 UTC, asimbera requested changes

2022-05-02 18:58 UTC, asimbera commented on src/pages/authentication/Verify.tsx
> +          {/* alert notification starts*/}
No need to add customized notifications. We will add those overlay notifications via some library. No need to waste time here.

2022-05-02 18:58 UTC, asimbera commented on src/pages/authentication/Verify.tsx
> +import { Link } from 'react-router-dom';
Please do not keep unused imports.

2022-05-02 19:11 UTC, thatsuman commented on src/pages/authentication/Verify.tsx
> +          {/* alert notification starts*/}
Okay I'll remove it by tomorrow.

2022-05-03 20:46 UTC, asimbera approved these changes
Looks good.

2022-05-03 20:47 UTC, merged